### PR TITLE
Added 'errored' state for steps.

### PR DESCRIPTION
**Pull request by Ledivin**
This was a required change for an upcoming EdgeManager feature, so I updated all tests, documentation, and demo in an attempt to have it pulled into PX.

The new "errored" state is exclusive to the "completed" state, and steps cannot have both at the same time - completing the current step will remove it from errored, and erroring a state will remove it from completed.

Our primary use-case is delayed data validation.

### CODE REVIEW

**Comment by Ledivin** [comment]
How do I go about signing the CLA?  I can't find any documentation on this.

**Comment by ColinEberhardt** [comment]
Just FYI, I'm the maintainer of cla-bot, this PR appeared in my error log alerts. I've just investigated, and the cause of failure. The commits in this PR are from people that do not have an associated GitHub account, so cannot be cross-checked against your cla-bot config. 

Perhaps I should allow verification by email address as well as GitHub login.

**Comment by sks** [comment]
@ColinEberhardt : Thanks for the insight :)


@Ledivin : Could you please squash/ ` use --reset-author ` to redo the commits using your github id ?

You can sign the CLA [here](https://www.predix-ui.com/#/develop/cla)

**Comment by Ledivin** [comment]
@sks @ColinEberhardt - I signed the CLA, squashed my commits, and updated the author information of the final commit, but cla-bot is still not recognizing me.  Am I missing something?

Also, according to Travis, the last two builds off of master failed for the same reason as this PR.

**Comment by sks** [comment]
@cla-bot check

**Comment by sks** [comment]
@ColinEberhardt : The check is failing because of the name having ` caps` .

https://github.com/ColinEberhardt/cla-bot/pull/82

**Comment by sks** [comment]
Fixing our Cloud functions to accommodate this 😢

**Comment by sks** [comment]
@cla-bot check

**Comment by sks** [comment]
px-step-pr-3


Thanks @Ledivin for the PR

**Comment by sks** [comment]
Thanks @Ledivin 👍 

Tagged [v1.1.4](https://github.com/predixdesignsystem/px-steps/releases/tag/v1.1.4)

**Pull request merged**
